### ISSUE TITLE
"So" rule not accurate

### ISSUE THREAD

**Issue by ChrisChinchilla** [testthedocs/Openly#10]
![Untitled](https://user-images.githubusercontent.com/42080/141130242-3d5ccda0-e5dc-4e49-b219-3283241d76f6.jpeg)

**Comment by dylan-k** [comment]
This might work as the regex to use instead:
`(?<=[.;?!]\s)(?:[.-]?\s*)so\b`

**Comment by ChrisChinchilla** [comment]
Thanks @dylan-k
