### ISSUE TITLE
reauthenticate

### ISSUE THREAD

**Issue by npivic** [testthedocs/Openly#12]
Hi! The word 'reauthenticate' triggered a `Did you really mean 'reauthenticate'?` message.

The word exists in Merriam-Webster, if that helps: https://www.merriam-webster.com/dictionary/reauthenticate

**Comment by ChrisChinchilla** [comment]
@npivic Hey! So, the accepted word lists typically comes from the host operating system's internal dictionary, which is typically something compatible with spell or hunspell and not always in sync with commercial dictionaries.

What i'd suggest is making a pull request adding the word to one of the custom word lists here - https://github.com/testthedocs/Openly/tree/master/Openly/tech-terms
