### ISSUE TITLE
Is the repo structured correctly?

### ISSUE THREAD

**Issue by dylan-k** [testthedocs/Openly#7]
I chose a particular file structure with #1 but having second thoughts, especially after looking at [the Google style](https://github.com/testthedocs/Google) that @ChrisChinchilla setup. 

Would it be easier to clone this repo into the user's vale styles directory if the .yml files were in the root? 

Would this play well with the config, testing files etc.?

**Comment by ChrisChinchilla** [comment]
Actually, you're probably right @dylan-k let me take a look at this one, as it's kind of my baby style anyway, there were going to be a bunch of follow up tasks for all of these transfers anyway, just need to think through everything.

**Comment by dylan-k** [comment]
ChrisChinchilla I can hold off on the pull requests while you think through everything. 

fwiw though I love the idea of being able to clone a style directly into Vale's styles directory. I have my styles directory as a git repo with sub repositories for the styles that can work that way, at least.
